// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	domain "tskmgr/Domain"

	mock "github.com/stretchr/testify/mock"
)

// JwtServiceInterface is an autogenerated mock type for the JwtServiceInterface type
type JwtServiceInterface struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: claims
func (_m *JwtServiceInterface) GenerateToken(claims *domain.Claims) (string, error) {
	ret := _m.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Claims) (string, error)); ok {
		return rf(claims)
	}
	if rf, ok := ret.Get(0).(func(*domain.Claims) string); ok {
		r0 = rf(claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*domain.Claims) error); ok {
		r1 = rf(claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateToken provides a mock function with given fields: tokenString
func (_m *JwtServiceInterface) ValidateToken(tokenString string) (*domain.Claims, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *domain.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Claims, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Claims); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJwtServiceInterface creates a new instance of JwtServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJwtServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *JwtServiceInterface {
	mock := &JwtServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
