// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	domain "tskmgr/Domain"

	mock "github.com/stretchr/testify/mock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// TaskUsecaseInterface is an autogenerated mock type for the TaskUsecaseInterface type
type TaskUsecaseInterface struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: task
func (_m *TaskUsecaseInterface) CreateTask(task *domain.Task) (*domain.Task, error) {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Task) (*domain.Task, error)); ok {
		return rf(task)
	}
	if rf, ok := ret.Get(0).(func(*domain.Task) *domain.Task); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTask provides a mock function with given fields: userrole, userid, title
func (_m *TaskUsecaseInterface) DeleteTask(userrole string, userid primitive.ObjectID, title string) error {
	ret := _m.Called(userrole, userid, title)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, primitive.ObjectID, string) error); ok {
		r0 = rf(userrole, userid, title)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllTasks provides a mock function with given fields:
func (_m *TaskUsecaseInterface) GetAllTasks() ([]domain.Task, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllTasks")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Task, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Task); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskByTitle provides a mock function with given fields: title
func (_m *TaskUsecaseInterface) GetTaskByTitle(title string) (*domain.Task, error) {
	ret := _m.Called(title)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByTitle")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Task, error)); ok {
		return rf(title)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Task); ok {
		r0 = rf(title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserTasks provides a mock function with given fields: userid
func (_m *TaskUsecaseInterface) GetUserTasks(userid primitive.ObjectID) ([]domain.Task, error) {
	ret := _m.Called(userid)

	if len(ret) == 0 {
		panic("no return value specified for GetUserTasks")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID) ([]domain.Task, error)); ok {
		return rf(userid)
	}
	if rf, ok := ret.Get(0).(func(primitive.ObjectID) []domain.Task); ok {
		r0 = rf(userid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(primitive.ObjectID) error); ok {
		r1 = rf(userid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTask provides a mock function with given fields: userrole, userid, title, newtask
func (_m *TaskUsecaseInterface) UpdateTask(userrole string, userid primitive.ObjectID, title string, newtask *domain.Task) (*domain.Task, error) {
	ret := _m.Called(userrole, userid, title, newtask)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string, primitive.ObjectID, string, *domain.Task) (*domain.Task, error)); ok {
		return rf(userrole, userid, title, newtask)
	}
	if rf, ok := ret.Get(0).(func(string, primitive.ObjectID, string, *domain.Task) *domain.Task); ok {
		r0 = rf(userrole, userid, title, newtask)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string, primitive.ObjectID, string, *domain.Task) error); ok {
		r1 = rf(userrole, userid, title, newtask)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskUsecaseInterface creates a new instance of TaskUsecaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskUsecaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskUsecaseInterface {
	mock := &TaskUsecaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
